[build]
builder = "nixpacks"
buildCommand = "npm install && ng build --configuration production"

[deploy]
startCommand = "npx serve -s dist/frontend -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000" 