[build]
builder = "nixpacks"
buildCommand = "npm install && ng build --configuration production"

[deploy]
startCommand = "npx serve -s dist/frontend"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production" 